# Generated by Django 5.0.6 on 2024-07-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pprice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
